Algoritmo "alturas"

Var

n, i : inteiro
alturaM, Paltura : inteiro

altura : vetor [0..9] de real
idade : vetor [0..9] de inteiro
nome : vetor [0..9] de caractere

Inicio

escreval("Quantas pessoas serão cadastradas? ")
leia(n)

para i de 0 ate n-1 faca
     escreval("Dados da pessoa: ")
        escreva("Nome: ")
        leia(nome[i])
        escreva("Idade: ")
        leia(idade[i])
        escreva("Altura: ")
        leia(altura[i])
fimpara





Fimalgoritmo